# Generated by Django 3.0.8 on 2020-08-21 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0019_auto_20200816_2035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryStatus', models.CharField(choices=[('Ready', 'Ready'), ('Waiting', 'Waiting')], default='Waiting', max_length=100)),
                ('managerNotes', models.CharField(blank=True, max_length=300, null=True)),
                ('confirmedOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=False)),
                ('pendingDelivery', models.IntegerField(default=0)),
                ('deliveryPartnerStatus', models.CharField(choices=[('Free', 'Free'), ('Engaged', 'Engaged'), ('Busy', 'Busy')], default='Free', max_length=100)),
                ('partnerLocation', models.CharField(blank=True, max_length=300)),
                ('deliveryPartner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartnerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryStatus', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=100)),
                ('confirmOTP', models.IntegerField(blank=True)),
                ('deliveryPartnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryPartnerProfile')),
                ('readyOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryManager')),
            ],
        ),
    ]
