# Generated by Django 3.0.8 on 2020-08-21 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0019_auto_20200816_2035'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryManager',
            new_name='DeliveryManagement',
        ),
        migrations.AlterField(
            model_name='deliverypartnerprofile',
            name='deliveryPartner',
            field=models.OneToOneField(limit_choices_to=models.Q(groups__name__icontains='Delivery-Partner'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
