# Generated by Django 3.0.8 on 2020-08-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200821_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymanagement',
            options={'ordering': ['-deliveryStatus', 'timestamp']},
        ),
    ]
