# Generated by Django 3.0.8 on 2020-08-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20200823_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartnerprofile',
            name='partnerLocation',
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='partnerLatitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='partnerLongitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='deliverymanagement',
            name='deliveryStatus',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Waiting', 'Waiting'), ('Preparing', 'Preparing')], default='Preparing', max_length=100),
        ),
    ]
