# Generated by Django 3.0.8 on 2020-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20200824_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymanagement',
            name='deliveryStatus',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Ready', 'Ready'), ('Waiting', 'Waiting'), ('Preparing', 'Preparing')], default='Preparing', max_length=100),
        ),
    ]
