# Generated by Django 3.0.8 on 2020-08-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20200824_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypartnerschedule',
            old_name='deliveryPartnerID',
            new_name='deliveryPartner',
        ),
        migrations.AlterField(
            model_name='deliverymanagement',
            name='deliveryStatus',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('Ready', 'Ready'), ('Waiting', 'Waiting'), ('Preparing', 'Preparing')], default='Preparing', max_length=100),
        ),
    ]
