# Generated by Django 3.0.8 on 2020-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20200825_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymanagement',
            options={'ordering': ['confirmedOrder']},
        ),
        migrations.RemoveField(
            model_name='deliverypartnerschedule',
            name='deliveryStatus',
        ),
        migrations.AlterField(
            model_name='deliverymanagement',
            name='deliveryStatus',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('OnShipping', 'OnShipping'), ('Ready', 'Ready'), ('Waiting', 'Waiting'), ('Preparing', 'Preparing'), ('Failed', 'Failed')], default='Preparing', max_length=100),
        ),
    ]
