# Generated by Django 3.0.8 on 2020-08-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20200825_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypartnerschedule',
            options={'ordering': ['-readyOrder']},
        ),
    ]
