# Generated by Django 3.0.8 on 2020-08-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20200825_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxDistance_1trip_KM', models.IntegerField(verbose_name='Max Distance (KM)  for 1 trip')),
                ('maxWeight_1trip_GRAM', models.IntegerField(verbose_name='Max Weight (Gram)  for 1 trip')),
                ('maxVolume_1trip_CC', models.IntegerField(verbose_name='Max Volume (CC)  for 1 trip')),
            ],
            options={
                'verbose_name': 'Delivery Limit Rule',
            },
        ),
    ]
