# Generated by Django 3.0.8 on 2020-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_deliverylimit_min_order_to_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymanagement',
            name='deliveryStatus',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Current', 'Current'), ('OnShipping', 'OnShipping'), ('Ready', 'Ready'), ('Waiting', 'Waiting'), ('Preparing', 'Preparing'), ('Failed', 'Failed')], default='Preparing', max_length=100),
        ),
    ]
