# Generated by Django 3.0.8 on 2020-08-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200726_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='goeswell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
