# Generated by Django 3.0.8 on 2020-08-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_goeswell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='goeswell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='well', to='product.Product'),
        ),
        migrations.CreateModel(
            name='GoesWellWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goeswellwith', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goeswellwith_product', to='product.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product')),
            ],
        ),
    ]
