# Generated by Django 3.0.8 on 2020-08-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='variant',
        ),
    ]
