# Generated by Django 3.0.8 on 2020-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_searchhistory_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
