# Generated by Django 3.0.8 on 2020-08-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_searchhistory_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='checked',
            new_name='searchedNow',
        ),
    ]
