# Generated by Django 3.0.8 on 2020-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200807_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='searchWord',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
