# Generated by Django 3.0.8 on 2020-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weightInGram',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='variants',
            name='weightInGram',
            field=models.IntegerField(default=100),
        ),
    ]
