# Generated by Django 3.0.8 on 2020-08-31 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_reserve',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.table'),
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.time_table'),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='hour_selection',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], unique=True, verbose_name='hour(s) of booking'),
        ),
    ]
