# Generated by Django 3.0.8 on 2020-08-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0002_auto_20200831_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_reserve',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Table'),
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Time_Table'),
        ),
    ]
