# Generated by Django 3.0.8 on 2020-09-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0003_auto_20200831_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='parent_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_reservation.Table'),
        ),
        migrations.AddField(
            model_name='time_table',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Table'),
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Time_Table'),
        ),
    ]
