# Generated by Django 3.0.8 on 2020-09-01 10:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0004_auto_20200901_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='seat',
            field=models.PositiveSmallIntegerField(verbose_name='No. of Seats/Table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Table'),
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Time_Table'),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='parent_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_reservation.Table'),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
