# Generated by Django 3.0 on 2023-06-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0006_auto_20200902_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_reserve',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Table'),
        ),
        migrations.AlterField(
            model_name='table_reserve',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_reservation.Time_Table'),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='parent_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_reservation.Table'),
        ),
    ]
