# Generated by Django 3.0.8 on 2020-08-08 07:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('span', models.IntegerField()),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
