# Generated by Django 3.0.8 on 2020-08-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20200808_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_duration',
            name='detail',
            field=models.CharField(max_length=200),
        ),
    ]
