# Generated by Django 3.0.8 on 2020-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_subscription_duration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
