# Generated by Django 3.0.8 on 2020-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_fine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_duration',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
