# Generated by Django 3.0.8 on 2020-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_subscription_duration_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_duration',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
