# Generated by Django 3.0.8 on 2020-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_subscription_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
