# Generated by Django 3.0.8 on 2020-08-11 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_auto_20200811_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_duration',
            name='count',
            field=models.IntegerField(default=999, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
