# Generated by Django 3.0.8 on 2020-08-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_reply'),
        ('offer', '0016_auto_20200811_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Variants')),
            ],
        ),
    ]
