# Generated by Django 3.0.8 on 2020-08-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_reply'),
        ('offer', '0017_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Variants'),
        ),
    ]
