# Generated by Django 3.0.8 on 2020-08-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_reply'),
        ('offer', '0018_auto_20200811_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
