# Generated by Django 3.0.8 on 2020-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_reply'),
        ('offer', '0019_auto_20200811_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productdiscount',
            unique_together={('product', 'variant')},
        ),
    ]
