# Generated by Django 3.0.8 on 2020-08-11 10:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_auto_20200811_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='discountPercent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='expiryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
