# Generated by Django 3.0.8 on 2020-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0022_auto_20200811_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused')], default='Active', max_length=10),
        ),
    ]
