# Generated by Django 3.0.8 on 2020-08-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0023_productdiscount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productdiscount',
            name='title',
        ),
    ]
