# Generated by Django 3.0.8 on 2020-08-15 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0025_cashbackcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackcoupon',
            name='title',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')]),
        ),
    ]
