# Generated by Django 3.0.8 on 2020-08-15 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0026_auto_20200815_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbackcoupon',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cashbackcoupon',
            name='cashBackstatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Expied', 'Expired')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashbackcoupon',
            name='title',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_0-9 -]*$', 'Only uppercase letters, numbers and underscores, hyphens are allowed.')]),
        ),
    ]
