# Generated by Django 3.0.8 on 2020-08-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0027_auto_20200815_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbackcoupon',
            old_name='title',
            new_name='code',
        ),
    ]
