# Generated by Django 3.0.8 on 2020-08-15 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0028_auto_20200815_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackcoupon',
            name='cashBackTimes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
