# Generated by Django 3.0.8 on 2020-08-27 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0029_cashbackcoupon_cashbacktimes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fine',
            options={'verbose_name': 'Rule'},
        ),
        migrations.AlterField(
            model_name='fine',
            name='minimumAmount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Amount'),
        ),
    ]
