# Generated by Django 3.0.8 on 2020-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_openinghours_specialdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdays',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
