# Generated by Django 3.0.8 on 2020-08-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200826_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialDays',
            new_name='SpecialDay',
        ),
    ]
