# Generated by Django 3.0.8 on 2020-08-08 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 13, 50, 31, 686294)),
        ),
    ]
