# Generated by Django 3.0.8 on 2020-08-08 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200808_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 13, 53, 27, 793159)),
        ),
    ]
