# Generated by Django 3.0.8 on 2020-08-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200808_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='end',
        ),
    ]
