# Generated by Django 3.0.8 on 2020-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_subscriber_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='BANKNAME',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='GATEWAYNAME',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='TXNDATE',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='TXNID',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='code',
            field=models.CharField(default=11111, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
