# Generated by Django 3.0.8 on 2020-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200808_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='user_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
