# Generated by Django 3.0.8 on 2020-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_subscriber_txnamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='user_ends',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
