# Generated by Django 3.0.8 on 2020-08-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200810_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='userEnds',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
