# Generated by Django 3.0.8 on 2020-08-10 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200810_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Failed', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='userEnds',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
