# Generated by Django 3.0.8 on 2020-08-10 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200810_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='userEnds',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
