# Generated by Django 3.0.8 on 2020-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200816_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cashBackTotal',
            field=models.FloatField(default=0),
        ),
    ]
