# Generated by Django 3.0.8 on 2020-08-16 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200816_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byCashBack', models.BooleanField()),
                ('cashBackCoupon', models.CharField(blank=True, max_length=100, null=True)),
                ('timeIssued', models.DateTimeField(default=datetime.datetime.now)),
                ('transactionAmount', models.FloatField(default=0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Wallet')),
            ],
        ),
    ]
