# Generated by Django 3.0.8 on 2020-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20200816_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='byCashBack',
            field=models.BooleanField(default=False),
        ),
    ]
