# Generated by Django 3.0.8 on 2020-08-17 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200816_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='BANKNAME',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='GATEWAYNAME',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='TXNAMOUNT',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='TXNDATE',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='TXNID',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='adminnote',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='code',
            field=models.CharField(blank=404, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='userEnds',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
