# Generated by Django 3.0.8 on 2020-08-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200817_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='userEnds',
        ),
    ]
