# Generated by Django 3.0.8 on 2020-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200818_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deliveryPartner_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='code',
            field=models.CharField(default=404, editable=False, max_length=10),
        ),
    ]
