# Generated by Django 3.0.8 on 2020-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='locationAddress',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
