# Generated by Django 3.0.8 on 2020-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_useraddress_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='color',
            field=models.CharField(default='#000000', max_length=18),
        ),
    ]
