# Generated by Django 3.0.8 on 2020-08-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_useraddress_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
