# Generated by Django 3.0.8 on 2020-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_paytm_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytm_data',
            name='MKEY',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='paytm_data',
            name='CALLBACK_URL',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='paytm_data',
            name='CHANNEL_ID',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='paytm_data',
            name='INDUSTRY_TYPE_ID',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='paytm_data',
            name='MID',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='paytm_data',
            name='WEBSITE',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
