# Generated by Django 3.0.8 on 2020-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200808_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discountOff',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='priceOffPlan',
            field=models.FloatField(default=0.0),
        ),
    ]
