# Generated by Django 3.0.8 on 2020-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200811_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discountOff',
            field=models.FloatField(default=0.0),
        ),
    ]
