# Generated by Django 3.0.8 on 2020-08-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_cashbackissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashBackIssuedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
