# Generated by Django 3.0.8 on 2020-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_cashbackissuedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashBackCoupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
