# Generated by Django 3.0.8 on 2020-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_cashbackcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='walletDeductionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='useWallet',
            field=models.BooleanField(default=False),
        ),
    ]
