# Generated by Django 3.0.8 on 2020-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_clientotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clientOTP',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
