# Generated by Django 3.0.8 on 2020-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200821_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clientOTP',
            field=models.CharField(blank=True, default='0000', max_length=10),
        ),
    ]
