# Generated by Django 3.0.8 on 2020-08-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_order_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
