# Generated by Django 3.0.8 on 2020-08-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20200824_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clientOTP',
            field=models.IntegerField(blank=True, default='0000'),
        ),
    ]
